action.yml

Partially ports ITK module template `build-test-package.yml` Github Action specification as a composite action that can be referenced by other projects in relation to [https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/131](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/131).
Notes:
- This is a first pass and will be tagged as a prerelease. Documentation indicates that the composite action cannot be tested in isolation, ~it may be necessary to pull this into `main` first and then test with a remote module development branch. [https://docs.github.com/en/actions/creating-actions/creating-a-composite-action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action)~
- A composite action runs in sequence and cannot run multiple …

ENH: Add cxx composite build action

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml

Migrate ITK C++ and Python Github CI procedures into reusable workflows that can be called and run by ITK external modules.
Partially addresses [https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/131](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/131).
Caveats:
1. Reusable workflows are only designed and tested for simple remote modules with no extra build steps.
2. Passing custom CMake arguments to a remote module build is feasible but untested. Custom CMake arguments should be considered not supported for this first iteration.
3. Remote modules depending on other remote modules or libraries are not currently supported. Modules with extra dependencies are responsible for implementing their own CI pipelines. The workflows here have been forked …

ENH: Add ITK C++ and Python CI Reusable Workflows

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml
action.yml

Write versions as strings rather than numbers because 3.1 != 3.10, etc.  Nothing is broken at present but in the future as, e.g., the Python version for some things goes from 3.8 to 3.9 to 3.10, this could end up being an unexpected problem.

ENH: Versions as strings, not numbers, so that 3.1 != 3.10, etc.

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml

Pending successful ITKSplitComponents test workflow run
https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3472832027

ENH: Bump for ITK v5.3rc04.post4

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml

Testing in ITKSplitComponents draft PR: https://github.com/InsightSoftwareConsortium/ITKSplitComponents/pull/65

ENH: Bump for ITK v5.3 release

---

.github/workflows/build-test-package-python.yml

Changes:
- Expose ITKPythonPackage organization and tag parameters to facilitate 1) testing ITKPythonPackage script updates from user forks and 2) applying ITKPythonPackage script patches introduced after packaging in ITKPythonBuilds archives
- Update `MANYLINUX_VERSION` parameter for Linux wheel build scripts
Depends on https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/233

ENH: Update for ITKPythonPackage script updates

---

.github/workflows/build-test-package-python.yml

Includes fix for gcc toolset compatibility
Depends on https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/239

ENH: Bump ITKPythonPackage tag

---

.github/workflows/build-test-cxx.yml

An issue has been observed where attempting to build modules with very large path lengths exceeds the Windows path length constraint for cxx builds. A fix is introduced where all cxx builds will use the working directory "im" for a shorter length.
See https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/20
Depends on https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/21

BUG: Resolve cxx Windows path length issue

---

.github/workflows/build-test-cxx.yml

This reverts commit 01d99733b66f3a76814a948ba425507420d6e477.
Several issues were observed for cxx tests across platform as a direct result of the changes in 01d9973, particularly regarding CDash paths and build scope. Changes should be reverted in the main branch while more investigation is done to address failures in separate development.
This is related to https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/20 and efforts related to using the reusable workflow for ITKMorphologicalContourInterpolation and other modules with long name lengths that interfere with Windows path length limits.

Revert "BUG: Resolve cxx Windows path length issue"

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml

Fix `Node.js` warnings linked to GitHub actions: transition to `actions/checkout@v3`, and `actions/setup-python@v4`.
Fixes:
```
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16:
actions/checkout@v2, actions/setup-python@v2, lukka/get-cmake@v3.22.2
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKIOMeshSTL/actions/runs/3791396544

ENH: Fix `Node.js` warnings linked to GitHub actions

---

.github/workflows/build-test-cxx.yml

For consistency with ITK C++ continuous integration workflow.
See https://github.com/InsightSoftwareConsortium/ITK/blob/master/Testing/ContinuousIntegration/AzurePipelinesLinux.yml#L29
Closes #4

ENH: Update to Python 3.9 in `build-test-cxx` workflow

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml

Fix `Node.js` warnings linked to CMake GitHub actions: transition to `lukka/get-cmake@v3.24.2`.
Fixes:
```
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16:
lukka/get-cmake@v3.22.2
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKBSplineGradient/actions/runs/3824095979
Cross-referencing
https://github.com/lukka/get-cmake/issues/46#issuecomment-1283449995
Left behind in commit 73e57e9.

ENH: Fix `Node.js` warnings linked to CMake GitHub actions

---

.github/workflows/build-test-package-python.yml

Fix `Node.js` warnings linked to artifact download GitHub actions: transition to `actions/download-artifact@v3`.
Fixes:
```
python-build-workflow / publish-python-packages-to-pypi
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/download-artifact@v2
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKTextureFeatures/actions/runs/3832886629
Cross-referencing
https://github.com/actions/download-artifact/pull/134
Left behind in commit 6e81bbd.

ENH: Fix Node.js warnings linked to artifact download GitHub actions

---

.github/workflows/build-test-package-python.yml
README.md

Exposes input parameter to allow the user to build for multiple Linux
toolsets and target architectures via available manylinux docker images.
Depends on ARM support introduced in ITKPythonPackage:
https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/236

ENH: Introduce manylinux option with ARM

---

.github/workflows/build-test-package-python.yml
README.md

Adds job to `build-test-package-python` workflow that retrieves a built Linux Python wheel artifact previously output by the workflow and uses it to test Jupyter Notebooks in the `examples/` folder of the external module.
For initial implementation only Linux wheels are tested with the Python version fixed at 3.10. To coincide with the Github Actions Linux runner image and machine architecture, only the `_2_28-x64` wheel is used.
Depends on #17. Tested in https://github.com/tbirdso/ITKSplitComponents/actions/runs/3843342651. Closes https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/49 .
EDIT: Note that the ITKSplitComponents test job [fails](https://github.com/tbirdso/ITKSplitComponents/actions/runs/3843342651/jobs/6546347627) because the …

ENH: Add Python Jupyter Notebook testing procedure

---

README.md
docs/CONTRIBUTING.md

DOC: Add documentation for community contributions

---

.github/workflows/build-test-package-python.yml

Adds step to validate that wheels are built successfully across platforms. Tailored to match granularity of build processes on each runner platform:
- Each Linux job expects one wheel output and verifies Python version, toolset, target platform, target architecture;
- Each Windows job expects one wheel output and verifies Python version, target platform;
- Each macOS job expects one wheel output per Python version (currently 3.7-3.11) and verifies target platform and wheel count
Addresses https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/issues/38
Tested at https://github.com/tbirdso/ITKSplitComponents/actions/runs/3931853870/jobs/6723658106

ENH: Validate wheel build output

---

.github/workflows/build-test-cxx.yml

Use specific XCode version 13.2 that is used in building ITK Python packages.
Tested at https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3969955914/jobs/6805099767

BUG: Match XCode version for ITK build

---

.github/workflows/build-test-package-python.yml

Job name was shortened for better display of the different jobs.
I took the time to address this because I was almost always hitting the 6h limit, e.g. [here](https://github.com/RTKConsortium/RTK/actions/runs/4170932015).
Successful run [here](https://github.com/RTKConsortium/RTK/actions/runs/4187870250).
Closes #32.

ENH: Split MacOS job into one job per Python version

---

.github/workflows/build-test-package-python.yml

CMake options were not passed to the Windows script for Python packaging. MacOS and Linux scripts work adequately. 
The '-DRTK_BUILD_APPLICATIONS:BOOL=OFF` option should turn off the compilation of applications using gengetopt and a simple search for ggo in the raw logs shows that it is the case for
https://github.com/RTKConsortium/RTK/actions/runs/4222316866/jobs/7330680579
and not before this commit
https://github.com/RTKConsortium/RTK/actions/runs/4201859054/jobs/7295273280.

BUG: Pass cmake-options to Windows script for Python module

---

.github/workflows/build-test-package-python.yml
README.md

Allows the user to specify `python3-minor-versions` to set Python 3.x targets for module wheel packaging. Python versions 3.7 through 3.11 are set as default according to Python maintenance schedule.
Notebook tests are also updated to test the x64 module wheel corresponding to the first specified Python version. Under previous behavior 3.10 packages were always selected for testing as it was assumed that 3.7 through 3.11 packages were always built. Updated behavior adapts to user requested versions.
https://devguide.python.org/versions/
Tests:
Defaults: https://github.com/tbirdso/ITKSplitComponents/actions/runs/4992038821
Request a single Python version: https://github.com/tbirdso/ITKSplitComponents/actions/runs/4992038821
Request a version subset, reordered so that a different version is …

ENH: Expose input parameter for Python versions

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml

RTK's GH actions were failing, see [here](https://github.com/RTKConsortium/RTK/actions/runs/5388515011). This patch seems to solve the issue, see [here](https://github.com/RTKConsortium/RTK/actions/runs/5443090881). I had encountered a similar issue before in Cuda GH actions ([here](https://github.com/RTKConsortium/RTK/blob/master/.github/workflows/build-test-cxx-cuda.yml#L81) and [here](https://github.com/RTKConsortium/RTK/blob/master/.github/workflows/build-test-package-python-cuda.yml#L101)), I don't know what triggers different behaviors...

COMP: Do not change location when launching VS development shell

---

.github/workflows/build-test-package-python.yml

The error message on the GitHub actions log was
[: missing `]'

BUG: Add missing space before closing bracket in if statements

---

.github/workflows/build-test-package-python.yml

Tested in https://github.com/tbirdso/ITKSplitComponents/actions/runs/5645479353
Closes #60
For merge into v5.4.0 milestone branch.

COMP: Remove Python 3.7 wheel builds for EOL

---

.github/workflows/build-test-package-python.yml

Prioritize `requirements.txt` file living alongside example notebooks for notebook testing.
Supports resolution for https://github.com/InsightSoftwareConsortium/ITKElastix/issues/262

ENH: Update notebook requirements search paths

---

.github/workflows/build-test-package-python.yml

Drop Python 3.7 from minor version list: Python 3.7 reached its EOL on 2023-06-27.

ENH: Drop Python 3.7 from minor version list

---

.github/workflows/build-test-cxx.yml

This gives us changes from PRs: https://github.com/InsightSoftwareConsortium/ITK/pull/4404 and https://github.com/InsightSoftwareConsortium/ITK/pull/4412 (among other things).

ENH: Update build-test-cxx.yml to latest ITK SHA

---

.github/workflows/build-test-cxx.yml

This depends on https://github.com/InsightSoftwareConsortium/ITK/pull/4425.

ENH: Update build-test-cxx.yml to avoid clang warning in a remote module

---

.github/workflows/build-test-package-python.yml

This change is required since InsightSoftwareConsortium/ITKPythonPackage@12af8e3b5be219e859266d28cc324d29af6489af
Without this change, the windows compilation was [failing](https://github.com/RTKConsortium/RTK/actions/runs/9383434085/job/25837037344#step:6:263). It is [successful](https://github.com/RTKConsortium/RTK/actions/runs/9384976262/job/25841997234#step:6:268) with it.

ENH: Put each Windows CMake option between quotes

---

.github/workflows/build-test-cxx.yml

Changes in this update:
https://github.com/actions/runner-images/commit/a615999e85d5b3f3853c691cd59fcfe89f0495ae#diff-d3119a278ce9ce80fc4b5af63a1112fb3a044aec3e6002d838e8eb26d7a3a499
Seem to cause segfault in test execution.

COMP: Avoid windows-2022 20240603.1.1 updates

---

.github/workflows/build-test-cxx.yml

This reverts commit 17e317843a6b0f953da17e8db8a56916acce3c97.
Reportedly resolved per @N-Dekker:
https://github.com/SuperElastix/elastix/pull/1151

Revert "COMP: Avoid windows-2022 20240603.1.1 updates"

---

README.md

Available for the reusable workflow with ITK 5.4.0 and greater.

DOC: Note support for macOS ARM Python packages

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml

Bump CMake and checkout GitHub actions versions.
Fixes:
```
cxx-build-workflow / build-test-cxx (ubuntu-22.04)
The following actions uses Node.js version which is deprecated and will be forced to run on node20:
lukka/get-cmake@v3.24.2.
For more info:
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
and
```
python-build-workflow / build-macos-py (8)
The following actions uses Node.js version which is deprecated and will be forced to run on node20:
actions/checkout@v3.
For more info:
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKAnalyzeObjectMap/actions/runs/10012233814

ENH: Bump CMake and checkout GitHub actions versions

---

.github/workflows/build-test-package-python.yml

Fixes the following error:
./macpython-download-cache-and-build-module-wheels.sh: line 81: /Users/svc-dashboard/D/P/ITKPythonPackage/scripts/macpython-install-python.sh: No such file or directory Building module wheels
./macpython-download-cache-and-build-module-wheels.sh: line 85: /Users/svc-dashboard/D/P/ITKPythonPackage/scripts/macpython-build-module-wheels.sh: No such file or directory

COMP: Use GNU tar and extract only relevant files

---

.github/workflows/build-test-cxx.yml
.github/workflows/build-test-package-python.yml

`std::filesystem` requires MACOSX_DEPLOYMENT_TARGET=10.15 or newer.

ENH: Enable specifying MacOSX deployment target

---

.github/workflows/build-test-cxx.yml

The macOS 12 runner image will be removed by December 3rd, 2024. To raise awareness of the upcoming removal, jobs using macOS 12 will temporarily fail during scheduled time periods defined below:
November 4, 9:00 AM - 7:00 PM EST
November 11, 9:00 AM - 7:00 PM EST
November 18, 9:00 AM - 7:00 PM EST
November 25, 9:00 AM - 7:00 PM EST
**What you need to do**
Jobs using the macos-12 YAML workflow label should be updated to macos-15, macos-14, macos-13, or macos-latest. You can always get up-to-date information on our tools by reading about the software in the [runner images](https://github.com/actions/runner-images) repository. Please contact GitHub Support if you run into any problems or need help.

ENH: Use macos-13 now to avoid disruption when macos-12 is retired

---

.github/workflows/build-test-cxx.yml

Incorporates libtiff symbol conflicts addressed in https://github.com/InsightSoftwareConsortium/ITK/pull/4958 which has started to cause issues on Windows builds.

COMP: Update C++ builds to use latest release-5.4 branch

---

.github/workflows/build-test-package-python.yml

macos-12 GitHub Runner images are no longer available in GitHub Actions.
With ITK 5.4.1, we will build packages compatible with the macos-13 images.

BUG: Disable Intel Mac Python package builds

---

.github/workflows/build-test-cxx.yml

Add macos-15 build and ITK5.4.2 tags.

ENH: Add builds for ITK-5.4.2

---

.github/workflows/build-test-package-python.yml

Note: Fixes were required for the `itk` `5.4.2` package, which were
published to PyPI and GitHub Releases as `5.4.2.post1`.

ENH: Update Python packages to build against ITK 5.4.2

---

.github/workflows/build-test-package-python.yml

Cross compilation of "_2_28-aarch64" packages is 10x slower than that of _2_28-x64 packages.
There are now ubuntu-22.04-arm runners. Compilation instead of cross-compilation reduces computation time from over 6h (see e.g. [here](https://github.com/RTKConsortium/RTK/actions/runs/13498284822/job/37710377078)) to 30 min (see [here](https://github.com/RTKConsortium/RTK/actions/runs/13525971209/job/37840116062)).
I don't have a machine to test the generated package, it would be great if someone could quickly test a Linux ARM package generated.

ENH: Compile Linux arm64 packages on arm64 github runners
